volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  django: &django
    image: ghcr.io/gidorah/personal_website:latest
    volumes:
      - production_django_media:/app/personal_website/media
    depends_on:
      - postgres
      - redis
    command: /start
    environment:
      # Add this section
      POSTGRES_USER: $$secrets.POSTGRES_USER
      POSTGRES_PASSWORD: $$secrets.POSTGRES_PASSWORD
      POSTGRES_DB: $$secrets.POSTGRES_DB
      POSTGRES_HOST: $$secrets.POSTGRES_HOST
      POSTGRES_PORT: '5432' # This one might be safe to hardcode
      DJANGO_SETTINGS_MODULE: config.settings.production #Probably not needed, as set on Dockerfile
      DJANGO_SECRET_KEY: $$secrets.DJANGO_SECRET_KEY
      DJANGO_ADMIN_URL: $$secrets.DJANGO_ADMIN_URL
      DJANGO_ALLOWED_HOSTS: $$secrets.DJANGO_ALLOWED_HOSTS
      DJANGO_SECURE_SSL_REDIRECT: 'False'
      DJANGO_ACCOUNT_ALLOW_REGISTRATION: 'True'
      WEB_CONCURRENCY: '4'
      SENTRY_DSN: $$secrets.SENTRY_DSN
      REDIS_URL: $$secrets.REDIS_URL
      CELERY_FLOWER_USER: $$secrets.CELERY_FLOWER_USER
      CELERY_FLOWER_PASSWORD: $$secrets.CELERY_FLOWER_PASSWORD

  postgres:
    image: ghcr.io/gidorah/personal_website_postgres:latest # GHCR image
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    environment:
      POSTGRES_USER: $$secrets.POSTGRES_USER
      POSTGRES_PASSWORD: $$secrets.POSTGRES_PASSWORD
      POSTGRES_DB: $$secrets.POSTGRES_DB

  traefik:
    image: ghcr.io/gidorah/personal_website_traefik:latest # GHCR Image
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celerybeat

  flower:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-flower

  nginx:
    image: ghcr.io/gidorah/personal_website_nginx:latest # GHCR Image
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
