volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  django: &django
    image: ghcr.io/gidorah/personal_website:latest
    volumes:
      - production_django_media:/app/personal_website/media
    depends_on:
      - postgres
      - redis
    command: /start
    env_file:
      - .env

  postgres:
    image: ghcr.io/gidorah/personal_website_postgres:latest
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - .env

  traefik:
    image: ghcr.io/gidorah/personal_website_traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    env_file:
      - .env
    ports:
      - '127.0.0.1:8080:80' # Expose Traefik's port 80 to localhost:8080
      - '127.0.0.1:8443:443' # Expose Traefik's port 443 to localhost:8443
      - '127.0.0.1:5555:5555'

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data
    env_file:
      - .env

  celeryworker:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celerybeat

  flower:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-flower

  nginx:
    image: ghcr.io/gidorah/personal_website_nginx:latest
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    env_file:
      - .env
