volumes:
  production_sqlite_data: {}

services:

  nextjs:
    build:
      context: .
      dockerfile: ./compose/production/Dockerfile
    image: personal_website_production_nextjs
    environment:
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
      - NODE_ENV=production
    expose:
      - 3000

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: personal_website_production_nginx
    depends_on:
      - nextjs
    ports:
      - '127.0.0.1:8082:80'
      - '127.0.0.1:8445:443'
    env_file:
      - .env
