services:
  django: &django
    build:
      context: ./backend
      dockerfile: ./compose/local/django/Dockerfile
    image: personal_website_local_django
    container_name: personal_website_local_django
    volumes:
      - ./backend:/app
      - local_sqlite_data:/app/data
    env_file:
      - ./backend/.envs/.local/.django
    ports:
      - '8000:8000'
      - '5678:5678' # Debug port
    environment:
      - REMOTE_DEBUGGING_PORT=5678
    command: /start

  nextjs:
    build:
      context: ./frontend
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: npm run dev

volumes:
  local_sqlite_data: {}
