volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  django: &django
    image: ghcr.io/gidorah/personal_website:latest
    volumes:
      - production_django_media:/app/personal_website/media
    depends_on:
      - postgres
      - redis
    command: /start

  postgres:
    image: ghcr.io/gidorah/personal_website_postgres:latest # GHCR image
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups

  traefik:
    image: ghcr.io/gidorah/personal_website_traefik:latest # GHCR Image
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: docker.io/redis:6

    volumes:
      - production_redis_data:/data

  celeryworker:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-celerybeat

  flower:
    <<: *django
    image: ghcr.io/gidorah/personal_website:latest
    command: /start-flower

  nginx:
    image: ghcr.io/gidorah/personal_website_nginx:latest # GHCR Image
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
