volumes:
  production_sqlite_data: {}

services:

  nextjs:
    image: ghcr.io/gidorah/personal_website_nextjs:latest
    environment:
      - NEXT_PUBLIC_SENTRY_DSN=${SENTRY_DSN}
    command: /start
    volumes:
      - ./frontend:/app
    ports:
      - '127.0.0.1:3000:3000'

  nginx:
    image: ghcr.io/gidorah/personal_website_nginx:latest
    depends_on:
      - nextjs
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
