volumes:
  production_sqlite_data: {}

services:
  django:
    build:
      context: ./backend
      dockerfile: ./compose/production/django/Dockerfile
    image: personal_website_production_django
    volumes:
      - production_sqlite_data:/app/data
    command: /start
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=personal_website.settings
      - BUILD_ENV=production
      - PYTHONPATH=/app

  nginx:
    build:
      context: ./backend
      dockerfile: ./compose/production/nginx/Dockerfile
    image: personal_website_production_nginx
    depends_on:
      - django
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
    env_file:
      - .env
