volumes:
  production_sqlite_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: personal_website_production_django
    volumes:
      - production_sqlite_data:/app
    command: /start
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: personal_website_production_nginx
    depends_on:
      - django
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
    env_file:
      - .env
