volumes:
  production_sqlite_data: {}

services:
  django:
    image: ghcr.io/gidorah/personal_website_django:latest
    volumes:
      - production_sqlite_data:/app/data
    command: /start
    environment:
      - DJANGO_SETTINGS_MODULE=personal_website.settings
      - BUILD_ENV=production
      - PYTHONPATH=/app
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SECURE_SSL_REDIRECT=${DJANGO_SECURE_SSL_REDIRECT:-False}
      - WEB_CONCURRENCY=${WEB_CONCURRENCY:-4}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS}
      - SENTRY_DSN=${SENTRY_DSN}

  nginx:
    image: ghcr.io/gidorah/personal_website_nginx:latest
    depends_on:
      - django
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
