volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

  production_redis_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: personal_website_production_django
    volumes:
      - production_django_media:/app/personal_website/media
    command: /start
    env_file:
      - .env

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: personal_website_production_nginx
    depends_on:
      - django
    ports:
      - '127.0.0.1:8080:80'
      - '127.0.0.1:8443:443'
    env_file:
      - .env
