services:

  nextjs:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    command: pnpm dev

volumes:
  local_sqlite_data: {}
