#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Create data directory if it doesn't exist
mkdir -p /app/data

python /app/manage.py migrate
python /app/manage.py collectstatic --noinput

exec gunicorn personal_website.wsgi:application --bind 0.0.0.0:5000
