import Nav from "@/components/nav";
import { workSans } from "@/components/ui/fonts";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased bg-[#fffbee]`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
