name: Deploy to Hetzner VPS

on:
  push:
    branches:
      - main
      - 14-get-rid-of-django-cookicutter

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # - name: Build and Push Django Image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ./backend
      #     file: ./backend/compose/production/django/Dockerfile
      #     push: true
      #     platforms: linux/arm64,linux/amd64
      #     tags: ghcr.io/${{ github.repository_owner }}/personal_website_django:latest
      
      - name: Build and Push Next.js Image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/compose/production/Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/personal_website_nextjs:latest

      - name: Build and Push Nginx Image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/compose/production/nginx/Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ghcr.io/${{ github.repository_owner }}/personal_website_nginx:latest

      - name: Copy compose file to server
        uses: appleboy/scp-action@v0.1.7 # Or another SCP action
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: 'docker-compose.production.yml'
          target: '~/personal_website'

      - name: Deploy to Hetzner via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

            # Pull the Django image (which contains docker-compose.yml)
            docker pull ghcr.io/${{ github.repository_owner }}/personal_website_nextjs:latest

            # Set environment variables and run docker compose
            # export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
            # export DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}
            export CSRF_TRUSTED_ORIGINS=${{ secrets.CSRF_TRUSTED_ORIGINS }}
            export SENTRY_DSN=${{ secrets.SENTRY_DSN }}

            # Change directory to the personal_website directory
            cd ~/personal_website

            # Stop and remove the previous containers
            docker compose -f docker-compose.production.yml down

            # Now we can use docker compose
            docker compose -f docker-compose.production.yml pull
            docker compose -f docker-compose.production.yml up -d --build
