name: Deploy to Hetzner VPS

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Placeholder Step
        run: echo "Workflow started. Deployment steps will be added here."
